[workspace]
authors = ["JoerivanEngelen <joeri.vanengelen@deltares.nl>"]
channels = ["conda-forge"]
name = "NHI_sprint_2026"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
convert = {cmd = "python convert.py", description = "Convert iMOD5 data to MODFLOW 6 and MetaSwap model."}

[dependencies]
bottleneck = "*"
geopandas = ">=1.0.0"
netCDF4 = "*"
loguru = "*"
numpy = ">=2.0"
pydantic = ">=2.11.0"
python = ">=3.10"
xarray = ">=2025.8.0"
scipy = "*"
tomli = "*"
tomli-w = "*"
xmipy = "*"
ribasim = "=2025.6.0"
plum-dispatch = "*"
rasterio = ">=1.5.0,<2"
rioxarray = ">=0.22.0,<0.23"
ipykernel = ">=7.2.0,<8"
jupyter = ">=1.1.1,<2"

[feature.github.pypi-dependencies]
xugrid = { git = "https://github.com/Deltares/xugrid.git" }
imod_coupler = { git = "https://github.com/Deltares/imod_coupler.git"}
primod ={ git = "https://github.com/Deltares/imod_coupler.git", subdirectory = "pre-processing" }
imod  = { git = "https://github.com/Deltares/imod-python.git" }


[feature.profile.dependencies]
snakeviz = "*"

[feature.build.dependencies]
git = "*"
python-build = "*"

[feature.build.pypi-dependencies]
xugrid = { path = "c:/ProgramData/DevDrive/clones_for_dist/xugrid/dist/xugrid-0.15.2-py3-none-any.whl" }
imod_coupler = { path = "c:/ProgramData/DevDrive/clones_for_dist/imod_coupler/dist/imod_coupler-2024.3.0-py3-none-any.whl" }
primod ={ path = "c:/ProgramData/DevDrive/clones_for_dist/imod_coupler/pre-processing/dist/primod-2024.3.0-py3-none-any.whl" }
imod  = { path = "c:/ProgramData/DevDrive/clones_for_dist/imod-python/dist/imod-1.0.1.dev1-py3-none-any.whl" }

[feature.build.tasks]
clone_imod = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist && git clone https://github.com/Deltares/imod-python.git"}
clone_xugrid = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist && git clone https://github.com/Deltares/xugrid.git"}
clone_coupler = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist && git clone https://github.com/Deltares/imod_coupler.git"}
pull_imod = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist/imod-python && git pull"}
pull_xugrid = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist/xugrid && git pull"}
pull_coupler = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist/imod_coupler && git pull"}
build_imod = {cmd = "cd c://ProgramData/DevDrive/clones_for_dist/imod-python && python -m build", depends-on = ["pull_imod"], description = "Build the iMOD Python package."}
build_xugrid ={ cmd = "cd c://ProgramData/DevDrive/clones_for_dist/xugrid && python -m build", depends-on = ["pull_xugrid"], description = "Build the xugrid Python package."}
build_coupler ={ cmd = "cd c://ProgramData/DevDrive/clones_for_dist/imod_coupler && python -m build", depends-on = ["pull_coupler"], description = "Build the imod_coupler Python package."}
build_primod ={ cmd = "cd c://ProgramData/DevDrive/clones_for_dist/imod_coupler/pre-processing && python -m build", depends-on = ["pull_coupler"], description = "Build the primod Python package."}
build_for_pack = {depends-on = ["build_imod", "build_xugrid", "build_primod", "build_coupler"]}
pack = { cmd = "pixi-pack --create-executable --environment build pixi.toml"}

[environments]
default = { features = ["github"], solve-group = "conda-deps" }
build ={ features = ["build"], solve-group = "build-deps" }
profile = { features = ["profile"], solve-group = "conda-deps" }